### ISSUE TITLE
[Question] Kernel version

### ISSUE THREAD

**Issue by jumptiger66** [itorK/leds-lp5569#1]
Hi, itorK
    Thank you for your wonderful work.
    Can you tell me the linux kernel verison that this repo work for ?

Regards

**Comment by itorK** [comment]
should work with the latest openwrt version

**Comment by jumptiger66** [comment]
Hello, I use it in the kernel 4.19 successfully. However, it will flash white when the board bootloader is up.  It doesn't seem to be controlled by the engine. I can't close it anyway unless I set each channel brightness to zero. 
I check the init code and be confused with it. Do you know why this happen?

**Comment by jumptiger66** [comment]
In addition, before running the engine, the white keeps flashing. After running the engine, the loaded pattern will be present with the white flashing effect. When I set the brightness of all channels to 0 before running the engine, and then load pattern, pattern can run independently. So,  except for the white flash of startup, kernel 4.19 can be adapted to this driver.

**Comment by jumptiger66** [comment]
Okey，I find the root cause. When I register the lp5569 led in device tree, I add the linux default-trigger="timer". This trigger will cause the default white blinking.
